- name: Install & setup
  hosts: localhost

  tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
        # Basic
          - vim
          - git
          - zsh
          - tar
        # Neovim
          - npm
          - python3
          - golang
          - tree-sitter-cli
        # Virtualisation
          - docker.io
          - virt-manager
        # Programs
          - emacs
          - lf
          - kitty
          - mpd
          - ncmpcpp
          - ripgrep
        # Sway
          - tofi
          - sway
          - swaylock
          - waybar
          - mako-notifier
          - wlogout
          - wlsunset
          - light
          - brightnessctl
        state: latest

    - name: Make sure local bin exists
      ansible.builtin.file:
        path: $HOME/.local/bin
        state: directory
    - name: Add user to groups
      become: true
      ansible.builtin.user:
        name: floor
        append: true
        groups: docker,video,input
    - name: Disable system mpd service
      become: true
      ansible.builtin.systemd_service:
        state: stopped
        enabled: false
        name: mpd.service
    - name: Disable system mpd socket
      become: true
      ansible.builtin.systemd_service:
        state: stopped
        enabled: false
        name: mpd.socket
    - name: Enable user mpd socket
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        scope: user
        name: mpd.socket
    - name: Enable user mpd service
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        scope: user
        name: mpd.socket

    - name: Check if nix is installed
      ansible.builtin.stat:
        path: /nix
      register: nix_result
    - name: Install nix
      become: true
      ansible.builtin.shell: |
        curl -L https://nixos.org/nix/install | sh -s -- --daemon --yes
      when: not nix_result.stat.exists
    # neovim
    - name: Check if neovim is installed
      ansible.builtin.stat:
        path: $HOME/.nix-profile/bin/nvim
      register: nvim_result
    - name: Install neovim
      ansible.builtin.shell: |
        /nix/var/nix/profiles/default/bin/nix profile add nixpkgs#neovim --extra-experimental-features nix-command --extra-experimental-features flakes
      when: not nvim_result.stat.exists
    # pistol
    - name: Check if pistol is installed
      ansible.builtin.stat:
        path: $HOME/.nix-profile/bin/pistol
      register: pistol_result
    - name: Install pistol
      ansible.builtin.shell: |
        /nix/var/nix/profiles/default/bin/nix profile add nixpkgs#pistol --extra-experimental-features nix-command --extra-experimental-features flakes
      when: not pistol_result.stat.exists
    # texlive
    - name: Check if texlive is installed
      ansible.builtin.stat:
        path: $HOME/.nix-profile/bin/latex
      register: texlive_result
    - name: Install texlive
      ansible.builtin.shell: |
        /nix/var/nix/profiles/default/bin/nix profile install nixpkgs#texliveMedium --extra-experimental-features nix-command --extra-experimental-features flakes
      when: not texlive_result.stat.exists

    - name: Dotfiles
      ansible.builtin.git:
        repo: 'https://github.com/datwinz/dotfiles'
        dest: ~/.cfg
        bare: true
    - name: Check if dotfiles have been checked out (~/.spacemacs)
      ansible.builtin.stat:
        path: $HOME/.spacemacs
      register: stat_result
    - name: Checkout dotfiles
      ansible.builtin.shell: |
        [[ -f $HOME/.bashrc ]] && mv $HOME/.bashrc $HOME/.bashrc.bak
        [[ -f $HOME/.zshrc ]] && mv $HOME/.zshrc $HOME/.zshrc.bak
        git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout linux
      when: not stat_result.stat.exists

    - name: Check if oh-my-zsh has been installed (~/.oh-my-zsh/README.md)
      ansible.builtin.stat:
        path: $HOME/.oh-my-zsh/README.md
      register: omz_result
    - name: Install oh-my-zsh
      ansible.builtin.shell: |
        rm -r $HOME/.oh-my-zsh
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        git --git-dir=$HOME/.cfg/ --work-tree=$HOME restore $HOME/.oh-my-zsh/custom/customzshrc.zsh
        git --git-dir=$HOME/.cfg/ --work-tree=$HOME restore $HOME/.oh-my-zsh/custom/themes/customhalf-life.zsh-theme
        git --git-dir=$HOME/.cfg/ --work-tree=$HOME restore $HOME/.zshrc
        git clone https://github.com/MichaelAquilina/zsh-you-should-use.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/you-should-use
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
        git --git-dir=$HOME/.cfg/ --work-tree=$HOME config --local status.showUntrackedFiles no
        mkdir $HOME/.ssh
      when: not omz_result.stat.exists

    - name: Change shell to zsh
      become: true
      ansible.builtin.user:
        name: floor
        shell: /bin/zsh

    - name: Check if spacemacs has been installed ($HOME/.emacs.d/spacemacs.mk)
      ansible.builtin.stat:
        path: $HOME/.emacs.d/spacemacs.mk
      register: space_result
    - name: Install spacemacs
      ansible.builtin.shell: |
        git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
      when: not space_result.stat.exists
