- name: Install
  hosts: localhost

  tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          - vim
          - git
          - zsh
          - docker.io
          - virt-manager
          - emacs
          - lf
          - flatpak
        state: latest
    - name: Install flatpaks
      community.general.flatpak:
        name: io.neovim.nvim
        state: present
    - name: Dotfiles
      ansible.builtin.git:
        repo: 'https://github.com/datwinz/dotfiles'
        dest: ~/.cfg
        bare: true
    - name: Check if dotfiles have been checked out
      ansible.builtin.stat:
        path: $HOME/.spacemacs
      register: stat_result
    - name: Checkout dotfiles
      ansible.builtin.shell: |
        [[ -f $HOME/.bashrc ]] && mv $HOME/.bashrc $HOME/.bashrc.bak
        [[ -f $HOME/.zshrc ]] && mv $HOME/.zshrc $HOME/.zshrc.bak
        git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout linux_void
      when: not stat_result.stat.exists
    - name: Check if oh-my-zsh has been installed
      ansible.builtin.stat:
        path: $HOME/.oh-my-zsh/README.md
      register: omz_result
    - name: Install oh-my-zsh
      ansible.builtin.shell: |
        rm -r $HOME/.oh-my-zsh
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        git --git-dir=$HOME/.cfg/ --work-tree=$HOME restore $HOME/.oh-my-zsh/custom/customzshrc.zsh
        git --git-dir=$HOME/.cfg/ --work-tree=$HOME restore $HOME/.oh-my-zsh/custom/themes/customhalf-life.zsh-theme
        git --git-dir=$HOME/.cfg/ --work-tree=$HOME restore $HOME/.zshrc
        git clone https://github.com/MichaelAquilina/zsh-you-should-use.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/you-should-use
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
        git --git-dir=$HOME/.cfg/ --work-tree=$HOME config --local status.showUntrackedFiles no
        mkdir $HOME/.ssh
      when: not omz_result.stat.exists
    - name: Change shell to zsh
      become: true
      ansible.builtin.shell: |
        chsh -s /bin/zsh floor
    - name: Check if spacemacs has been installed
      ansible.builtin.stat:
        path: $HOME/.emacs.d/spacemacs.mk
      register: space_result
    - name: Install spacemacs
      ansible.builtin.shell: |
        git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
      when: not space_result.stat.exists
